-- Mise à jour des frais de livraison (sans recréer tables ni policies)
-- Supabase → SQL Editor → Run (réexécutable à volonté)

insert into public.localities (id, name_fr, name_en, zone_group, shipping_fee) values
  ('yoff', 'Yoff', 'Yoff', 'dakar-1500', 1500),
  ('mermoz', 'Mermoz / Sacré-Cœur', 'Mermoz / Sacré-Cœur', 'dakar-1500', 2000),
  ('plateau', 'Plateau', 'Plateau', 'dakar-2000', 3000),
  ('medina', 'Médina', 'Médina', 'dakar-2000', 2000),
  ('fann', 'Fann / Point E / Amitié', 'Fann / Point E / Amitié', 'dakar-2000', 2000),
  ('hlm', 'HLM / Grand Dakar', 'HLM / Grand Dakar', 'dakar-2000', 2000),
  ('liberte', 'Liberté / Sicap', 'Liberté / Sicap', 'dakar-2000', 2000),
  ('dieuppeul', 'Dieuppeul / Derklé', 'Dieuppeul / Derklé', 'dakar-2000', 2000),
  ('colobane', 'Colobane / Fass', 'Colobane / Fass', 'dakar-2000', 2000),
  ('camberene', 'Cambérène', 'Cambérène', 'dakar-2000', 2000),
  ('ouakam', 'Ouakam / Mamelles', 'Ouakam / Mamelles', 'dakar-2500', 2500),
  ('almadies', 'Almadies / Ngor', 'Almadies / Ngor', 'dakar-2500', 2500),
  ('mariste', 'Mariste / Hann', 'Mariste / Hann', 'dakar-2500', 2500),
  ('patte-oie', 'Patte d''Oie / Foire', 'Patte d''Oie / Foire', 'dakar-2500', 2500),
  ('pikine', 'Pikine', 'Pikine', 'dakar-3000', 3000),
  ('guediawaye', 'Guédiawaye', 'Guédiawaye', 'dakar-3500', 2500),
  ('parcelles', 'Parcelles Assainies', 'Parcelles Assainies', 'dakar-3500', 3500),
  ('thiaroye-gare', 'Thiaroye Gare', 'Thiaroye Gare', 'dakar-3500', 3500),
  ('rufisque', 'Rufisque', 'Rufisque', 'rufisque-4000', 3000),
  ('keur-massar', 'Keur Massar', 'Keur Massar', 'rufisque-4000', 4000),
  ('mbao', 'Mbao', 'Mbao', 'rufisque-4000', 4000),
  ('yeumbeul', 'Yeumbeul / Malika', 'Yeumbeul / Malika', 'rufisque-4000', 4000),
  ('bargny', 'Bargny / Diamniadio', 'Bargny / Diamniadio', 'rufisque-4000', 4000),
  ('thies', 'Thiès', 'Thiès', 'thies-mbour', 4000),
  ('mbour', 'Mbour / Saly', 'Mbour / Saly', 'thies-mbour', 4000),
  ('saint-louis', 'Saint-Louis', 'Saint-Louis', 'regions', 5000),
  ('touba', 'Touba / Diourbel', 'Touba / Diourbel', 'regions', 5000),
  ('kaolack', 'Kaolack / Fatick', 'Kaolack / Fatick', 'regions', 5000),
  ('ziguinchor', 'Ziguinchor / Casamance', 'Ziguinchor / Casamance', 'regions', 5000),
  ('tambacounda', 'Tambacounda / Kédougou', 'Tambacounda / Kédougou', 'regions', 5000),
  ('kolda', 'Kolda / Sédhiou', 'Kolda / Sédhiou', 'regions', 5000),
  ('matam', 'Matam / Podor', 'Matam / Podor', 'regions', 5000),
  ('louga', 'Louga / Linguère', 'Louga / Linguère', 'regions', 5000),
  ('autre-region', 'Autre localité régionale', 'Other regional location', 'regions', 5000)
on conflict (id) do update set
  name_fr = excluded.name_fr,
  name_en = excluded.name_en,
  zone_group = excluded.zone_group,
  shipping_fee = excluded.shipping_fee,
  active = true;
